### ISSUE TITLE
Add URL Dialog (Clipboard Insert)

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#38] opened 2019-01-01 03:58 UTC
Please consider adding a checkbox option to "Insert URLs in Clipboard to the Add URL dialog".
That would add links in the Windows Clipboard to the URL(s) field by default.

**Comment by smaragdus** [comment] 2019-01-02 03:13
I think this is a duplicate of #7.

**Closed** 2021-07-08 13:57 UTC
