### ISSUE TITLE
Dark mode works only in "portable" mode

### ISSUE THREAD

**Issue by martymarty004** [erickutcher/httpdownloader#207] opened 2022-04-14 19:03 UTC
I downloaded the latest DM version of HTTP Downloader (v1.0.4.9), but I found out that it only works correctly after you configure the program in Portable mode by adding the `portable` file where the executable is.

I use the program in portable mode, so this isn't an issue for me, but I wanted to report it anyway.

Also, I think that you should write somewhere what is the difference between the different executables (Default, DM, LS), because it wasn't clear at first.

![image](https://user-images.githubusercontent.com/61474670/163458292-30c5ff9d-ff2c-4496-b0e8-5bbeffde5e15.png)

![image](https://user-images.githubusercontent.com/61474670/163458361-610b2e4a-2622-4121-bf69-9997642eed4b.png)

**Comment by erickutcher** [comment] 2022-04-16 03:51
I see what the problem is. The "dark_mode" file should be in the AppData folder where the settings are if you're not using portable mode. I need to change it so that it reads it from the same directory as the program.

The Dark Mode build uses unsupported API functions and so it may or may not work going forward. That's the primary reason why I haven't documented it. The Log Support build is mostly for debugging purposes and I don't expect many would need to use it.

**Comment by martymarty004** [comment] 2022-04-16 18:24
OK, thank you.
Should I close this issue now, or are you going to close it with a PR?

**Comment by erickutcher** [comment] 2022-04-17 03:23
I'll close it when I do a new release, but since this isn't a priority fix, it'll probably be some time from now.

**Comment by erickutcher** [comment] 2022-09-02 20:10
A new version is up that should fix this.

**Closed** 2024-04-10 18:19 UTC
Labels: bug, fixed
